models/EmulatorParams.php
<?php

namespace app\models;

use yii\base\Model;



class EmulatorParams extends Model
{
    public $xheHost;

    public $fbLogin;

    public $fbPassword;

    public $proxy;


    public function bindTestParams()
    {
        $this->xheHost = \Yii::$app->request->hostName == 'fbhuman.dev' ? '192.168.56.101:7017' : '85.114.11.38:47017';

        /*$this->xheHost = '85.114.11.38:47017';
        $this->fbLogin = 'zhdanova.iulya2017@yandex.ru';
        $this->fbPassword = 'DY901XH2';
        $this->proxy = '185.128.212.2:9450@user283:39dkfjfj';


        $this->xheHost = '192.168.56.101:7017';
        $this->fbLogin = 'profaller@bk.ru';
        $this->fbPassword = 'digitaL9';
        $this->proxy = '185.128.212.2:9450@user283:39dkfjfj';*/
    }

    public function rules()
    {
        return [
            [['xheHost', 'fbLogin', 'fbPassword', 'proxy'], 'required'],
        ];
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            ['rememberMe', 'boolean'],
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findOne(['login' => $this->username]);
        }

        return $this->_user;
    }
}

models/User.php
<?php

namespace app\models;

use app\enums\Role;
use Yii;

/**
 * This is the model class for table "users".
 *
 * @property integer $id
 * @property string $role
 * @property string $login
 * @property string $email
 * @property string $name
 * @property string $password
 * @property string $token
 * @property string $auth_key
 * @property string $created_at
 */
class User extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    public static function tableName()
    {
        return 'users';
    }

    public function rules()
    {
        return [
            [['login', 'email'], 'trim'],
            [['login', 'role'], 'required'],

            [['password'], 'required', 'on' => ['insert']],
            [['password'], 'string', 'min' => 3],

            ['login', 'unique', 'on' => 'default'],
            ['email', 'email'],
            [['email', 'login', 'name'], 'string', 'max' => 255]
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'role' => 'Role',
            'login' => 'Login',
            'email' => 'Email',
            'name' => 'Name',
            'password' => 'Password',
            'token' => 'Token',
            'auth_key' => 'Auth Key',
            'created_at' => 'Created At',
        ];
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->auth_key = Yii::$app->getSecurity()->generateRandomString();
            $this->password = Yii::$app->getSecurity()->generatePasswordHash($this->password);
            $this->token = Yii::$app->getSecurity()->generateRandomString();
        } else if (!empty($this->password) && $this->password != $this->oldAttributes['password']) {
            $this->password = Yii::$app->getSecurity()->generatePasswordHash($this->password);
            $this->token = Yii::$app->getSecurity()->generateRandomString();
        }

        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $attr)
    {
        if ($insert) {
            Yii::$app->authManager->assign(Yii::$app->authManager->getRole($this->role), $this->id);
        }
    }

    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['token' => $token]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }
}

controllers/PanelController.php
<?php

namespace app\controllers;

use app\components\WebController;
use app\services\Process;
use app\services\ServerService;

class PanelController extends WebController
{

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionStopServer()
    {
        return $this->json(['success' => ServerService::create()->stopServer()]);
    }

    public function actionStartServer()
    {
        $proc = ServerService::create()->startServer();
        return $this->json([
            'success' => $proc->status(),
            'pid' => $proc->getPid(),
            'savedPid' => ServerService::create()->getSavedPid(),
            'ps aux' => (new Process('ps aux | grep server/start'))->start(false),
            'procResult' => $proc->getResult(),
            'host' => \Yii::$app->request->hostName,
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionOffline()
    {
        $this->layout = 'offline';

        return '';
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'FBaccs Emulator',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Panel', 'url' => ['/panel/index']],

            /*['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )*/
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/offline.php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 26.07.16
 * Time: 16:37
 */

views/panel/index.php
<?php

use app\components\SocketServer;
use app\models\EmulatorParams;
use app\services\ServerService;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */

$model = new EmulatorParams();
$model->bindTestParams();

?>


<div class="panel-index" data-app-controller="panel_startFrom">

    <div data-app-controller="panel_ServerControls" data-is-running="<?= Json::encode(ServerService::create()->isServerRun())?>">
        <button
                data-href="<?= Url::toRoute(['panel/start-server']) ?>"
                data-disable-text="Server running..."
                data-normal-text="Run"
                class="btn btn-success js-start">Start</button>

        <button data-href="<?= Url::toRoute(['panel/stop-server']) ?>" class="btn btn-danger js-stop">Stop</button>
    </div>
    <br>

    <?php $form = ActiveForm::begin([
        'action' => Url::toRoute(['/panel/start']),
        'options' => [
                'class' => 'form form-inline'
        ]
    ])?>

        <?= $form->field($model, 'xheHost')?>
        <?= $form->field($model, 'fbLogin')?>
        <?= $form->field($model, 'fbPassword')?>
        <?= $form->field($model, 'proxy')?>

        <div class="form-group" style="vertical-align: top">
            <?= Html::submitButton('Begin emulation', [
                'class' => 'btn btn-primary',
                'data-loading-text' => 'Running...'
            ])?>
        </div>

    <?php ActiveForm::end()?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">Log</div>
        </div>
        <div class="panel-body js-log">

        </div>
    </div>

    <script>
        window.serverUri = '<?= 'ws://' . \Yii::$app->request->hostName . ':' . SocketServer::SERVER_PORT ?>';
    </script>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <div>
            <?= Html::errorSummary($model)?>
        </div>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('login')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Sign in', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->